"""empty message

Revision ID: 02cd17647853
Revises: e9fb147fc4bc
Create Date: 2020-12-08 02:44:16.348614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cd17647853'
down_revision = 'e9fb147fc4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.Enum('Reviewing', 'Approved', 'Disapproved', 'Complete', 'Incomplete'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
