"""empty message

Revision ID: 0cc459dc1f06
Revises: 3ef6552de055
Create Date: 2020-12-15 13:07:23.214248

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '0cc459dc1f06'
down_revision = '3ef6552de055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'uuid')
    # ### end Alembic commands ###
