"""empty message

Revision ID: 3ef493f117b1
Revises: b098d19bfe5c
Create Date: 2020-12-17 23:04:00.768167

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3ef493f117b1'
down_revision = 'b098d19bfe5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('ident_name', sa.String(length=100), nullable=False))
    # op.create_unique_constraint(None, 'kyc', ['ident_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kyc', type_='unique')
    op.drop_column('kyc', 'ident_name')
    # ### end Alembic commands ###
