"""empty message

Revision ID: 3ef6552de055
Revises: 709aa5ce270f
Create Date: 2020-12-15 13:07:10.103524

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3ef6552de055'
down_revision = '709aa5ce270f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('uuid', mysql.VARCHAR(length=100), nullable=False))
    # ### end Alembic commands ###
