"""empty message

Revision ID: 6f690c6fc72c
Revises: 959bff62220e
Create Date: 2020-12-15 11:09:11.815576

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f690c6fc72c'
down_revision = '959bff62220e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('task', 'date')
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.DATE(), nullable=False))
    op.add_column('task', sa.Column('date', mysql.VARCHAR(length=255), nullable=False))
    op.alter_column('task', 'user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
