"""empty message

Revision ID: 709aa5ce270f
Revises: c8c2fea609d4
Create Date: 2020-12-15 12:56:26.943134

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '709aa5ce270f'
down_revision = 'c8c2fea609d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_comment', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('ticket_comment_ibfk_2', 'ticket_comment', type_='foreignkey')
    op.create_foreign_key(None, 'ticket_comment', 'user', ['user_id'], ['id'], ondelete='cascade')
    op.drop_column('ticket_comment', 'admin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_comment', sa.Column('admin_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ticket_comment', type_='foreignkey')
    op.create_foreign_key('ticket_comment_ibfk_2', 'ticket_comment', 'user', ['admin_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ticket_comment', 'user_id')
    # ### end Alembic commands ###
