"""empty message

Revision ID: 8cde01a9c42f
Revises: 8acdb2386955
Create Date: 2020-12-15 02:10:46.466228

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8cde01a9c42f'
down_revision = '8acdb2386955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'uuid')
    # ### end Alembic commands ###
