"""empty message

Revision ID: aa51be792cd1
Revises: bd521a3a68b8
Create Date: 2020-12-10 11:45:34.638081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa51be792cd1'
down_revision = 'bd521a3a68b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('project_team', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint('project_team_ibfk_2', 'project_team', type_='foreignkey')
    op.create_foreign_key(None, 'project_team', 'team', ['team_id'], ['id'], ondelete='cascade')
    op.drop_column('project_team', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_team', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_team', type_='foreignkey')
    op.create_foreign_key('project_team_ibfk_2', 'project_team', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_team', 'team_id')
    op.drop_table('member_project')
    # ### end Alembic commands ###
