"""empty message

Revision ID: bd521a3a68b8
Revises: ea2f5b71c256
Create Date: 2020-12-10 07:58:50.969091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd521a3a68b8'
down_revision = 'ea2f5b71c256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('due_date', sa.Date(), nullable=False))
    op.add_column('project', sa.Column('start_date', sa.Date(), nullable=False))
    op.drop_column('project', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('date', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'due_date')
    # ### end Alembic commands ###
