"""empty message

Revision ID: e9fb147fc4bc
Revises: 5dfba487ff2d
Create Date: 2020-12-05 02:25:29.600520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9fb147fc4bc'
down_revision = '5dfba487ff2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kyc', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('kyc', sa.Column('updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kyc', 'updated')
    op.drop_column('kyc', 'created')
    # ### end Alembic commands ###
