"""empty message

Revision ID: fd24d63e4f89
Revises: aa51be792cd1
Create Date: 2020-12-10 12:12:51.776904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd24d63e4f89'
down_revision = 'aa51be792cd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'schedule_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('schedule_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
